:PROPERTIES:
:ID:       951af047-42b8-4bed-8cb5-827eb6ba0756
:END:
#+TITLE: Category Theory 이해
#+author: xroger88
#+categories: programming concept
#+tags: category theory
#+description: Category Theory for Programmers, written by Bartosz Milewski

ggg

* Category : the essence of composition
Category theory is about composing arrows.

* Types and Functions
** Types are about composbility

operational semantics vs. denotational semantics

A factorial function has an obvious mathematical denotation. An astute reader
might ask: What’s the mathematical model for reading a character from
the keyboard or sending a packet across the network? For the longest
time that would have been an awkward question leading to a rather convoluted explanation. It seemed like denotational semantics wasn’t the
best fit for a considerable number of important tasks that were essential
for writing useful programs, and which could be easily tackled by operational semantics. The breakthrough came from category theory. Eugenio Moggi discovered that computational effect can be mapped to monads. This turned out to be an important observation that not only gave
denotational semantics a new lease on life and made pure functional
programs more usable, but also shed new light on traditional programming.

** pure and dirty functions
** example of types

empty set type is called "bottom" in math.
how to represent that type? nothing meaningful in programming language but in math.

single-elemnt set type is called "singlton", for example, void type.
f :: void -> integer, f :: integer -> void
not meaningful in programming but possible in math.

two-element set type, for example, bool type is that. True or False. Predicates
is one of fucntions returning boolean type.

* Category Great and Small
