#+TITLE: Notes on programming language features
#+AUTHOR: xroger88
#+TAGS: programming language
#+DESCRIPTION: 프로그래밍 언어 학습 노트

book introduction.
...

* Introduction
A peronsal study on programming lanaguage features such as procedual vs. declative,
static typing vs. dyanamic typing, strong typing vs. weak typing,
obejct-oriendted vs. functional programming and so on.

* [Book] Languages mentioned in the book named "Seven Languages in Seven Weeks" authored by Bruce A. Tate
- Ruby
- Io
- Prolog
- Scala
- Erlang
- Clojure
- Haskell


* [Book] Land of Lisp - Learn to Program in Lisp, One game at a Time! authord by Conrad Barski
This book helps me to understand the basic concept of Lisp and details on Common
Lisp (CLISP). It shows the power of Lisp language by taking an example of
making a simple game.

* [Video] Interested on Clojure CONJ 2019
- [[https://www.youtube.com/watch?v=OUZZKtypink&list=PLZdCLR02grLqSy15ALLAZDU6LGpAJDrAQ&index=12&t=0s][Sherlock Holmes, Consulting Developer]] - Stuart Halloway
- [[https://www.youtube.com/watch?v=GvJm-eJ5o18&list=PLZdCLR02grLqSy15ALLAZDU6LGpAJDrAQ&index=3&t=0s][The Hitchhikers Guide to Multiparadigm Programming]] - Ariel Ortiz
